import { criarObraPersistida, salvarEtapa, salvarPendencia, salvarRdo, salvarMaterial, salvarModeloBim, salvarAnaliseBim, criarProjetoBimPersistido, salvarModeloBimProjeto, salvarAnaliseBimProjeto, salvarFrente, salvarMedicao, salvarContrato, salvarAditivoContrato, salvarLancamentoFinanceiro, salvarFolhaPagamento } from '../../storage/sqliteStore.js';

export function carregarDemoOperacional(db) {
  const obraId = 'demo-obra-001';
  const frente = salvarFrente(db, obraId, { id: 'demo-frente-estrutura', nome: 'Estrutura · Pavimento 02', responsavel: 'Equipe estrutural', percentualConcluido: 38 });
  salvarMedicao(db, obraId, { id: 'demo-medicao-001', frenteId: frente, descricao: 'Armadura de pilares do pavimento 02', unidade: 'kg', quantidade: 850, precoUnitario: 7.8, periodo: '2026-08', status: 'enviada' });
  const contrato = salvarContrato(db, obraId, { id: 'demo-contrato-001', fornecedor: 'Concreto Horizonte (fictício)', objeto: 'Fornecimento de concreto usinado fck 30 MPa', valor: 86400, inicio: '2026-07-01', fim: '2026-12-31' });
  salvarAditivoContrato(db, contrato, { id: 'demo-aditivo-001', descricao: 'Acréscimo de volume para fundações', valor: 7200, data: '2026-08-10' });
  salvarLancamentoFinanceiro(db, { id: 'demo-lanc-receita', obraId, tipo: 'receita', categoria: 'Medição', descricao: 'Medição contratual · agosto', valor: 125000, vencimento: '2026-08-30', status: 'previsto' });
  salvarLancamentoFinanceiro(db, { id: 'demo-lanc-despesa', obraId, tipo: 'despesa', categoria: 'Materiais', descricao: 'Aço CA-50 e concreto', valor: 67200, vencimento: '2026-08-20', status: 'pago' });
  salvarFolhaPagamento(db, { id: 'demo-folha-001', obraId, colaborador: 'Carlos Souza (fictício)', periodo: '2026-08', funcao: 'Encarregado', valorBruto: 6800, status: 'previsto' });
}

export function carregarDemoBimIndependente(db) {
  const estudo = criarProjetoBimPersistido(db, { id: 'demo-bim-001', nome: 'Compatibilização demo · Estrutura x Hidráulica', descricao: 'Estudo independente para demonstração do fluxo BIM.' });
  const estrutura = salvarModeloBimProjeto(db, estudo, { nome: 'estrutura-demo.ifc', arquivoNome: 'estrutura-demo.ifc', disciplina: 'Estrutura', elementos: [{ globalId: 'EST-VIGA-B2', ifcClass: 'IfcBeam', name: 'Viga B2 · Pavimento 02', bbox: { min: [0, 0, 2.8], max: [4, .3, 3.1] } }, { globalId: 'EST-PILAR-P4', ifcClass: 'IfcColumn', name: 'Pilar P4', bbox: { min: [1.5, 0, 0], max: [1.8, .3, 3.1] } }] });
  const hidraulica = salvarModeloBimProjeto(db, estudo, { nome: 'hidraulica-demo.ifc', arquivoNome: 'hidraulica-demo.ifc', disciplina: 'Hidráulica', elementos: [{ globalId: 'HID-TUB-025', ifcClass: 'IfcPipeSegment', name: 'Tubo de água fria DN25', bbox: { min: [1.4, -.1, 2.9], max: [4.2, .2, 3.05] } }, { globalId: 'HID-TUB-050', ifcClass: 'IfcPipeSegment', name: 'Tubo de esgoto DN50', bbox: { min: [5, 1, 2.5], max: [6, 1.2, 2.7] } }] });
  salvarAnaliseBimProjeto(db, estudo, { modeloAId: estrutura, modeloBId: hidraulica, modo: 'intersection', conflitos: [{ indice: 1, modo: 'intersection', aGlobalId: 'EST-VIGA-B2', bGlobalId: 'HID-TUB-025', aClasse: 'IfcBeam', bClasse: 'IfcPipeSegment', aNome: 'Viga B2 · Pavimento 02', bNome: 'Tubo de água fria DN25', ponto: [2.7, .05, 2.98], distanciaM: 0, gravidade: 'high', status: 'aberto' }] });
}
export function carregarDemo(db) {
  const id = criarObraPersistida(db, { id: 'demo-obra-001', codigo: 'DEMO-001', nome: 'Residencial Jardim das Acácias — Demonstração', cliente: 'Construtora Horizonte (fictício)', responsavelTecnico: 'Eng. Marina Costa (fictício)', status: 'em_execucao', dataInicio: '2026-07-01', dataPrevisaoTermino: '2027-02-28' });
  salvarEtapa(db, id, { nome: 'Fundação', percentualPeso: 25, percentualConcluido: 72, status: 'em_andamento', responsavel: 'Equipe de fundações' }); salvarEtapa(db, id, { nome: 'Estrutura', percentualPeso: 35, percentualConcluido: 38, status: 'em_andamento', responsavel: 'Equipe estrutural' }); salvarEtapa(db, id, { nome: 'Instalações', percentualPeso: 25, percentualConcluido: 15, status: 'em_andamento', responsavel: 'Instalações prediais' }); salvarEtapa(db, id, { nome: 'Acabamentos', percentualPeso: 15, percentualConcluido: 0, status: 'nao_iniciada', responsavel: 'A contratar' });
  salvarPendencia(db, id, { descricao: 'Revisar interferência entre tubulação e viga do pavimento 02', prioridade: 'alta', responsavel: 'Eng. Marina', origem: 'bim' }); salvarPendencia(db, id, { descricao: 'Confirmar entrega dos esquadros da fachada', prioridade: 'media', responsavel: 'Suprimentos', origem: 'obra' });
  salvarRdo(db, id, { data: '2026-08-14', turno: 'Diurno', responsavel: 'Carlos Souza (fictício)', clima: { condicao: 'Ensolarado, 24 °C' }, equipes: [{ funcao: 'Pedreiros', quantidade: 6 }, { funcao: 'Armadores', quantidade: 4 }], servicosExecutados: [{ descricao: 'Montagem das armaduras dos pilares do eixo B' }, { descricao: 'Concretagem das sapatas S12 a S16' }], materiaisRecebidos: [{ material: 'Aço CA-50', quantidade: 850, unidade: 'kg' }, { material: 'Concreto usinado', quantidade: 18, unidade: 'm³' }], ocorrencias: [], impedimentos: [], fotos: [], observacoes: 'Registro fictício para demonstração.' });
  salvarMaterial(db, id, { material: 'Concreto estrutural fck 30 MPa', unidade: 'm³', quantidadePlanejada: 240, quantidadeRealizada: 86, custoUnitario: 480 }); salvarMaterial(db, id, { material: 'Aço CA-50', unidade: 'kg', quantidadePlanejada: 18000, quantidadeRealizada: 6400, custoUnitario: 7.8 });
  const estrutura = salvarModeloBim(db, id, { nome: 'estrutura-demo.ifc', arquivoNome: 'estrutura-demo.ifc', disciplina: 'Estrutura', elementos: [{ globalId: 'EST-VIGA-B2', ifcClass: 'IfcBeam', name: 'Viga B2 — Pavimento 02', bbox: { min: [0, 0, 2.8], max: [4, .3, 3.1] } }, { globalId: 'EST-PILAR-P4', ifcClass: 'IfcColumn', name: 'Pilar P4', bbox: { min: [1.5, 0, 0], max: [1.8, .3, 3.1] } }] });
  const hidraulica = salvarModeloBim(db, id, { nome: 'hidraulica-demo.ifc', arquivoNome: 'hidraulica-demo.ifc', disciplina: 'Hidráulica', elementos: [{ globalId: 'HID-TUB-025', ifcClass: 'IfcPipeSegment', name: 'Tubo de água fria DN25', bbox: { min: [1.4, -.1, 2.9], max: [4.2, .2, 3.05] } }, { globalId: 'HID-TUB-050', ifcClass: 'IfcPipeSegment', name: 'Tubo de esgoto DN50', bbox: { min: [5, 1, 2.5], max: [6, 1.2, 2.7] } }] });
  salvarAnaliseBim(db, id, { modeloAId: estrutura, modeloBId: hidraulica, modo: 'intersection', conflitos: [{ indice: 1, modo: 'intersection', aGlobalId: 'EST-VIGA-B2', bGlobalId: 'HID-TUB-025', aClasse: 'IfcBeam', bClasse: 'IfcPipeSegment', aNome: 'Viga B2 — Pavimento 02', bNome: 'Tubo de água fria DN25', ponto: [2.7, .05, 2.98], distanciaM: 0, gravidade: 'high', status: 'aberto' }] }); return id;
}
