// Pórtico espacial linear com 6 graus de liberdade por nó.
// A rigidez é formulada no eixo local e transformada para coordenadas globais.

function solve(matrix, vector) { const a = matrix.map((row, i) => [...row, vector[i]]); const n = vector.length; for (let p = 0; p < n; p += 1) { let best = p; for (let r = p + 1; r < n; r += 1) if (Math.abs(a[r][p]) > Math.abs(a[best][p])) best = r; if (Math.abs(a[best][p]) < 1e-12) throw new Error('Pórtico espacial instável ou com apoios insuficientes.'); [a[p], a[best]] = [a[best], a[p]]; for (let r = p + 1; r < n; r += 1) { const f = a[r][p] / a[p][p]; for (let c = p; c <= n; c += 1) a[r][c] -= f * a[p][c]; } } const x = Array(n).fill(0); for (let r = n - 1; r >= 0; r -= 1) x[r] = (a[r][n] - a[r].slice(r + 1, n).reduce((s, v, j) => s + v * x[r + j + 1], 0)) / a[r][r]; return x; }
function zeros(size) { return Array.from({ length: size }, () => Array(size).fill(0)); }
function transpose(a) { return a[0].map((_, c) => a.map((row) => row[c])); }
function multiply(a, b) { return a.map((row) => b[0].map((_, c) => row.reduce((sum, value, i) => sum + value * b[i][c], 0))); }
function add(matrix, dofs, local) { for (let i = 0; i < dofs.length; i += 1) for (let j = 0; j < dofs.length; j += 1) matrix[dofs[i]][dofs[j]] += local[i][j]; }
function cross(a, b) { return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]]; }
function norm(a) { return Math.hypot(...a); }
function unit(a) { const length = norm(a); return a.map((v) => v / length); }
function localAxes(direction) { const x = unit(direction); const reference = Math.abs(x[2]) < 0.9 ? [0, 0, 1] : [0, 1, 0]; const z = unit(cross(x, reference)); const y = unit(cross(z, x)); return [x, y, z]; }
function transformation(axes) { const t = zeros(12); for (let node = 0; node < 2; node += 1) for (let block = 0; block < 2; block += 1) for (let i = 0; i < 3; i += 1) for (let j = 0; j < 3; j += 1) t[node*6 + block*3 + i][node*6 + block*3 + j] = axes[i][j]; return t; }
function localStiffness(E, G, A, Iy, Iz, J, L) { const k = zeros(12); const axial = E*A/L; const torsion = G*J/L; const by = E*Iz; const bz = E*Iy; const l2 = L**2; const l3 = L**3; const set = (i,j,v) => { k[i][j] += v; }; set(0,0,axial); set(0,6,-axial); set(6,0,-axial); set(6,6,axial); set(3,3,torsion); set(3,9,-torsion); set(9,3,-torsion); set(9,9,torsion); const cy=[[12*by/l3,6*by/l2,-12*by/l3,6*by/l2],[6*by/l2,4*by/L,-6*by/l2,2*by/L],[-12*by/l3,-6*by/l2,12*by/l3,-6*by/l2],[6*by/l2,2*by/L,-6*by/l2,4*by/L]]; const iy=[1,5,7,11]; const cz=[[12*bz/l3,-6*bz/l2,-12*bz/l3,-6*bz/l2],[-6*bz/l2,4*bz/L,6*bz/l2,2*bz/L],[-12*bz/l3,6*bz/l2,12*bz/l3,6*bz/l2],[-6*bz/l2,2*bz/L,6*bz/l2,4*bz/L]]; const iz=[2,4,8,10]; for (let r=0;r<4;r+=1) for (let c=0;c<4;c+=1) { k[iy[r]][iy[c]]+=cy[r][c]; k[iz[r]][iz[c]]+=cz[r][c]; } return k; }
function elementMatrix(element, nodes) { const a=nodes.get(element.nodeI); const b=nodes.get(element.nodeJ); if (!a || !b) throw new Error(`Elemento ${element.id} referencia nó inexistente.`); const direction=[Number(b.x)-Number(a.x),Number(b.y)-Number(a.y),Number(b.z)-Number(a.z)]; const L=norm(direction); const E=Number(element.E); const G=Number(element.G ?? E/(2*(1+0.2))); const A=Number(element.A); const Iy=Number(element.Iy ?? element.I ?? 1e-5); const Iz=Number(element.Iz ?? element.I ?? 1e-5); const J=Number(element.J ?? Iy+Iz); if (!(L>0) || ![E,G,A,Iy,Iz,J].every((v)=>v>0)) throw new Error(`Elemento ${element.id} possui geometria ou propriedades inválidas.`); const axes=localAxes(direction); const t=transformation(axes); const local=localStiffness(E,G,A,Iy,Iz,J,L); return { length:L, global:multiply(transpose(t),multiply(local,t)) }; }
export function analisarPorticoEspacial3D(modelo = {}) { const nodes=new Map((modelo.nos??[]).map((n)=>[n.id,n])); const elements=modelo.elementos??[]; if(nodes.size<2||!elements.length) throw new Error('O pórtico espacial precisa de nós e elementos.'); const ids=[...nodes.keys()]; const idx=new Map(ids.flatMap((id,p)=>['ux','uy','uz','rx','ry','rz'].map((d,i)=>[`${id}:${d}`,p*6+i]))); const size=ids.length*6; const K=zeros(size); const F=Array(size).fill(0); const fixed=new Set(); for(const node of nodes.values()){ const loads=node.loads??{}; for(const d of ['x','y','z']) F[idx.get(`${node.id}:u${d}`)]=Number(loads[`f${d}`]??0); for(const d of ['ux','uy','uz','rx','ry','rz']) if(node.supports?.[d]) fixed.add(idx.get(`${node.id}:${d}`)); } const details=elements.map((element)=>{ const m=elementMatrix(element,nodes); const dofs=[...['ux','uy','uz','rx','ry','rz'].map((d)=>idx.get(`${element.nodeI}:${d}`)),...['ux','uy','uz','rx','ry','rz'].map((d)=>idx.get(`${element.nodeJ}:${d}`))]; add(K,dofs,m.global); return { id:element.id,length:m.length }; }); if(!fixed.size) throw new Error('Defina pelo menos um apoio espacial.'); for(const d of fixed){ for(let i=0;i<size;i+=1){K[d][i]=0;K[i][d]=0;} K[d][d]=1;F[d]=0; } const u=solve(K,F); return { displacement:Object.fromEntries(ids.map((id)=>[id,{ux:u[idx.get(`${id}:ux`)],uy:u[idx.get(`${id}:uy`)],uz:u[idx.get(`${id}:uz`)],rx:u[idx.get(`${id}:rx`)],ry:u[idx.get(`${id}:ry`)],rz:u[idx.get(`${id}:rz`)]}])),dofCount:size,elements:details,avisos:['Pórtico espacial linear com transformação local/global. Verifique orientações, combinações, flambagem e efeitos de segunda ordem antes do uso profissional.'] }; }
